//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruiseDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string Fullname { get; set; }
        public string Position { get; set; }
        public Nullable<int> Ordering { get; set; }
    }
}
